In [1]:
from pathlib import Path
import sys

repo = Path("/Users/zombak/git/compresso")
sys.path.insert(0, str(repo / "examples"))

import compresso.clustering as cc
from compresso.io import load_srp_tensor
from recsys_lib.checkpoint import read_checkpoint, load_recsys_split

In [2]:


checkpoint = repo / "artifacts/goodbooks/exp_descriptions.zip"

with read_checkpoint(checkpoint) as root:
    split = load_recsys_split(root)
    srp = load_srp_tensor(root / "sbert_sae" / "sparse_embeddings.srp.pt")

item_ids = split["item_ids"]
tags = split["entity_tag_matrix"]
tag_names = split["tag_names"]
meta = split["entity_metadata"]

print(srp.shape)
print(tags.shape if tags is not None else None)
print(tag_names[:20] if tag_names is not None else None)
meta.head()

(10000, 4096)
(10000, 2816)
['00-in-class' '02-fantasy' '04-realistic-fiction' '1' '100-books'
 '100-books-to-read-before-you-die' '100-books-to-read-in-a-lifetime'
 '1001' '1001-books' '1001-books-to-read'
 '1001-books-to-read-before-you-die' '1001-books-you-must-read-before-you'
 '1001-import' '1001-list' '1001-to-read' '14th-century' '16th-century'
 '17th-century' '1800s' '18th-century']

,item_id,title,authors,average_rating,description
0,1,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.34,"""Immerse yourself in the thrilling world of Th..."
1,10,Pride and Prejudice,Jane Austen,4.24,"""Experience the timeless romance and wit of Ja..."
2,100,The Poisonwood Bible,Barbara Kingsolver,4.02,"""Immerse yourself in the epic tale of The Pois..."
3,1000,"Shadow and Bone (Shadow and Bone, #1)",Leigh Bardugo,4.05,"""Immerse yourself in the epic fantasy world of..."
4,10000,The First World War,John Keegan,4.00,"""Experience the definitive account of the Grea..."

In [4]:
meta[meta.description.notna()]

,item_id,title,authors,average_rating,description
0,1,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,4.34,"""Immerse yourself in the thrilling world of Th..."
1,10,Pride and Prejudice,Jane Austen,4.24,"""Experience the timeless romance and wit of Ja..."
2,100,The Poisonwood Bible,Barbara Kingsolver,4.02,"""Immerse yourself in the epic tale of The Pois..."
3,1000,"Shadow and Bone (Shadow and Bone, #1)",Leigh Bardugo,4.05,"""Immerse yourself in the epic fantasy world of..."
4,10000,The First World War,John Keegan,4.00,"""Experience the definitive account of the Grea..."
...,...,...,...,...,...
9995,9995,"Billy Budd, Sailor",Herman Melville,3.09,"""Experience the classic tale of loyalty, honor..."
9996,9996,"Bayou Moon (The Edge, #2)",Ilona Andrews,4.09,"""Immerse yourself in the mystical world of The..."
9997,9997,"Means of Ascent (The Years of Lyndon Johnson, #2)",Robert A. Caro,4.25,"""Means of Ascent: The Years of Lyndon Johnson,..."
9998,9998,The Mauritius Command,Patrick O'Brian,4.35,"""Embark on a thrilling adventure with ""The Mau..."
9999,9999,Cinderella Ate My Daughter: Dispatches from th...,Peggy Orenstein,3.65,"""Cinderella Ate My Daughter: Dispatches from t..."

In [99]:
checkpoint = repo / "artifacts/ml20m/exp_tags.zip"

with read_checkpoint(checkpoint) as root:
    split = load_recsys_split(root)
    srp = load_srp_tensor(root / "sae" / "sparse_embeddings.srp.pt")

item_ids = split["item_ids"]
tags = split["entity_tag_matrix"]
tag_names = split["tag_names"]
meta = split["entity_metadata"]

print(srp.shape)
print(tags.shape if tags is not None else None)
print(tag_names[:20] if tag_names is not None else None)
meta.head()

(20549, 4096)
(20549, 823)
['007' '01/11' '01/12' '02/11' '03/11' '04/11' '05/11' '06/11' '10/10'
 '100 essential female performances' '11/10' '11/11' '12/10' '12/11'
 '1930s' '1950s' '1960s' '1970s' '1980s' '19th century']

,item_id,title,genres,description
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Get ready for a rootin' tootin' good time with...
1,10,GoldenEye (1995),Action|Adventure|Thriller,"""Experience the high-stakes action and espiona..."
2,100,City Hall (1996),Drama|Thriller,"""Experience the gripping drama of City Hall, a..."
3,1000,Curdled (1996),Crime,"""Uncover the dark secrets of the past with Cur..."
4,100003,Up in Smoke (1957),Comedy,"""Get ready for a wild ride with the 1957 comed..."

In [3]:
meta.iloc[2815,-1]

'"Experience the heartwarming and inspiring story of Marty and her journey to the American frontier in "Love Comes Softly" by Janette Oke. After her husband\'s untimely death, Marty is left alone and pregnant, forced to marry the kind but rugged Clark Davis to secure a future for herself and her unborn child. As she navigates her new role as a stepmother to Clark\'s young daughter, Missie, Marty must confront her own doubts and fears, learning to find wholeness and love through patience, faith, and the power of human connection. A classic tale of hope, resilience, and the transformative power of love, "Love Comes Softly" is a timeless and captivating read that will leave you feeling uplifted and inspired."'

In [71]:
meta[meta.title.str.contains("ermin")]

,item_id,title,genres
1551,110026,Prison Terminal: The Last Days of Private Jack...,Crime|Documentary
2815,1240,"Terminator, The (1984)",Action|Sci-Fi|Thriller
3711,1738,Vermin (1998),Comedy
5058,26333,"Terminal Man, The (1974)",Sci-Fi|Thriller
6857,32851,Hotel Terminus: The Life and Times of Klaus Ba...,Documentary
9952,4934,"Exterminator, The (1980)",Action|Crime|Thriller|War
11084,548,Terminal Velocity (1994),Action|Mystery|Thriller
11424,563,Germinal (1993),Drama|Romance
11961,589,Terminator 2: Judgment Day (1991),Action|Sci-Fi
12498,61018,Peppermint Candy (Bakha satang) (1999),Drama
13326,6537,Terminator 3: Rise of the Machines (2003),Action|Adventure|Sci-Fi
13739,6738,Indiscretion of an American Wife (a.k.a. Termi...,Drama
13847,67949,"Exterminating Angels, The (anges exterminateur...",Drama|Fantasy|Romance
14024,68791,Terminator Salvation (2009),Action|Adventure|Sci-Fi|Thriller
17163,8241,Masterminds (1997),Action|Comedy|Thriller
17701,8529,"Terminal, The (2004)",Comedy|Drama|Romance
17885,8620,"Exterminating Angel, The (Ángel exterminador, ...",Comedy|Drama|Fantasy|Mystery
18447,88248,Quarantine 2: Terminal (2011),Horror|Mystery|Sci-Fi
19843,95752,Terminal USA (1993),Comedy
20332,98595,Peppermint Soda (Diabolo menthe) (1977),Comedy|Drama

In [3]:
meta = split["entity_metadata"]

# row index -> title
row_to_title = meta["title"].astype(str).to_numpy()

# title lowercase -> row indices
title_to_rows = {}
for i, title in enumerate(row_to_title):
    title_to_rows.setdefault(title.lower(), []).append(i)
def find_movies(query, limit=20):
    q = query.lower()
    hits = []
    for i, title in enumerate(row_to_title):
        if q in title.lower():
            hits.append((i, str(item_ids[i]), title, meta.iloc[i].get("genres", "")))
    return hits[:limit]

In [4]:
find_movies("Potter")

[(890,
  '18',
  'Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)',
  ''),
 (1112, '2', "Harry Potter and the Sorcerer's Stone (Harry Potter, #1)", ''),
 (1116, '2001', 'Harry Potter: Film Wizardry', ''),
 (1224,
  '21',
  'Harry Potter and the Order of the Phoenix (Harry Potter, #5)',
  ''),
 (1227, '2101', 'The Harry Potter Collection 1-4 (Harry Potter, #1-4)', ''),
 (1446,
  '23',
  'Harry Potter and the Chamber of Secrets (Harry Potter, #2)',
  ''),
 (1557, '24', 'Harry Potter and the Goblet of Fire (Harry Potter, #4)', ''),
 (1668, '25', 'Harry Potter and the Deathly Hallows (Harry Potter, #7)', ''),
 (1890, '27', 'Harry Potter and the Half-Blood Prince (Harry Potter, #6)', ''),
 (1941, '2745', "From Potter's Field (Kay Scarpetta, #6)", ''),
 (1990,
  '279',
  'Harry Potter and the Cursed Child - Parts One and Two (Harry Potter, #8)',
  ''),
 (2285,
  '3054',
  'Harry Potter and the Chamber of Secrets: Sheet Music for Flute with C.D',
  ''),
 (2530, '3275', 'Harry Potter Boxed Set, Books 1-5 (Harry Potter, #1-5)', ''),
 (3042,
  '3736',
  'Harry Potter Page to Screen: The Complete Filmmaking Journey',
  ''),
 (3061, '3753', 'Harry Potter Collection (Harry Potter, #1-6)', ''),
 (3455,
  '4107',
  'Harry Potter: A Pop-Up Book: Based on the Film Phenomenon',
  ''),
 (3515,
  '4161',
  "James Potter and the Hall of Elders' Crossing (James Potter, #1)",
  ''),
 (3580, '422', 'Harry Potter Boxset (Harry Potter, #1-7)', ''),
 (5715,
  '6141',
  'Harry Potter and the Order of the Phoenix (Harry Potter, #5, Part 1)',
  ''),
 (6033,
  '6428',
  'Short Stories from Hogwarts of Heroism, Hardship and Dangerous Hobbies (Pottermore Presents, #1)',
  '')]

In [268]:
import importlib
importlib.reload(cc)

ImportError: cannot import name 'filter_clusters_by_size' from 'compresso.clustering.merge' (/Users/zombak/git/compresso/src/compresso/clustering/merge.py)

In [57]:
clusters_iou = cc.cluster_srp(
    srp,
    mode="combo_signed",
    top_m=,
    combo_size,
    min_cluster_size=5,
    #activation_iou_threshold=0.5,
    #post_merge_min_cluster_size=5
    #entity_tag_matrix=tags,
    #tag_names=tag_names,
    #top_k_tags=20,
    #tag_similarity_threshold=0.8,
)

In [24]:
from functools import partial

clusters = cc.run_clustering_pipeline(
    srp,
    [
        partial(
            cc.build_activation_clusters,
            mode="combo_signed",
            top_m=8,
            combo_size=2,
            min_cluster_size=5,
        ),
        lambda c: cc.merge_clusters_by_entity_iou(c, threshold=0.25),
    ],
    verbose=True,
)

[cluster_pipeline] step 1/2: build_activation_clusters
[cluster_pipeline] step 1/2 done: clusters=4689
[cluster_pipeline] step 2/2: <lambda> clusters_in=4689
[cluster_pipeline] step 2/2 done: clusters=952

In [14]:
def show_movie_clusters(query):
    hits = find_movies(query)
    cidss =[]
    for row_idx, item_id, title, genres in hits:
        print("\nMOVIE", row_idx, item_id, title, "|", genres)

        cluster_ids = clusters.entity_to_cluster_ids.get(row_idx, [])
        if not cluster_ids:
            print("  no cluster")
            continue
        cids = []
        for cid in cluster_ids:
            c = clusters.cluster_by_id[cid]
            cids.append(cid)
            print(" ", cid, "n=", c.entity_count, "features=", len(c.centroid.indices))
            print("   tags:", ", ".join(f"{t.name}:{t.score:.3f}" for t in c.tags[:5]))
        cidss.append(cids)
    return cidss

In [59]:
MOVIE 384 1343 The Light Fantastic (Discworld, #2; Rincewind #2) | 
  no cluster

MOVIE 377 1337 Going Postal (Discworld, #33; Moist von Lipwig, #1) | 
  combo:930:neg&1580:pos n= 35 features= 2
   tags:

SyntaxError: invalid syntax (1267599386.py, line 1)

In [25]:
ll = show_movie_clusters("Discworld")

MOVIE 101 1089 Equal Rites (Discworld, #3; Witches #1) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 377 1337 Going Postal (Discworld, #33; Moist von Lipwig, #1) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 383 1342 Night Watch (Discworld, #29; City Watch, #6) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 384 1343 The Light Fantastic (Discworld, #2; Rincewind #2) |
  merge:merge_clusters_by_entity_iou:232 n= 10 features= 5
   tags:
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 411 1368 Small Gods (Discworld, #13) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 805 1722 The Wee Free Men (Discworld, #30; Tiffany Aching, #1) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 855 1768 Wyrd Sisters (Discworld, #6; Witches #2) |
  merge:merge_clusters_by_entity_iou:67 n= 118 features= 35
   tags:
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 1029 1924 Reaper Man (Discworld, #11; Death, #2) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 1162 2043 Men at Arms (Discworld, #15; City Watch #2) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 1209 2086 Hogfather (Discworld, #20; Death, #4) |
  merge:merge_clusters_by_entity_iou:232 n= 10 features= 5
   tags:
  merge:merge_clusters_by_entity_iou:234 n= 5 features= 4
   tags:
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 1235 2109 Sourcery (Discworld, #5; Rincewind #3) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 1415 2271 Feet of Clay (Discworld, #19; City Watch, #3) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 1616 2452 Pyramids (Discworld, #7) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 1634 2469 Lords and Ladies (Discworld, #14; Witches #4) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 1636 2470 Thud! (Discworld, #34; City Watch #7) |
  merge:merge_clusters_by_entity_iou:232 n= 10 features= 5
   tags:
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 1656 2489 Witches Abroad (Discworld, #12; Witches #3) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 1671 2501 Soul Music (Discworld, #16; Death, #3) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:
  combo:1070:neg&1171:pos n= 6 features= 2
   tags:

MOVIE 1729 2554 Monstrous Regiment (Discworld, #31; Industrial Revolution, #3) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 1793 2611 A Hat Full of Sky (Discworld, #32; Tiffany Aching, #2) |
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

MOVIE 1844 2658 Moving Pictures (Discworld, #10; Industrial Revolution, #1) |
  merge:merge_clusters_by_entity_iou:234 n= 5 features= 4
   tags:
  merge:merge_clusters_by_entity_iou:233 n= 49 features= 12
   tags:

In [26]:
show_cluster("merge:merge_clusters_by_entity_iou:233")

 merge:merge_clusters_by_entity_iou:233
n= 49
features= [(370, 0.2980000078678131), (960, 0.3709999918937683), (996, 0.06199999898672104), (1016, -0.12399999797344208), (1411, -0.1889999955892563), (1580, 0.40700000524520874), (2124, -0.3089999854564667), (2461, -0.06199999898672104), (2907, -0.09399999678134918), (3552, -0.1889999955892563), (3982, -0.5299999713897705), (4061, -0.35899999737739563)]
tags:
movies:
  101 1089 Equal Rites (Discworld, #3; Witches #1) |
  377 1337 Going Postal (Discworld, #33; Moist von Lipwig, #1) |
  383 1342 Night Watch (Discworld, #29; City Watch, #6) |
  384 1343 The Light Fantastic (Discworld, #2; Rincewind #2) |
  411 1368 Small Gods (Discworld, #13) |
  805 1722 The Wee Free Men (Discworld, #30; Tiffany Aching, #1) |
  855 1768 Wyrd Sisters (Discworld, #6; Witches #2) |
  1029 1924 Reaper Man (Discworld, #11; Death, #2) |
  1162 2043 Men at Arms (Discworld, #15; City Watch #2) |
  1209 2086 Hogfather (Discworld, #20; Death, #4) |
  1235 2109 Sourcery (Discworld, #5; Rincewind #3) |
  1415 2271 Feet of Clay (Discworld, #19; City Watch, #3) |
  1616 2452 Pyramids (Discworld, #7) |
  1634 2469 Lords and Ladies (Discworld, #14; Witches #4) |
  1636 2470 Thud! (Discworld, #34; City Watch #7) |
  1656 2489 Witches Abroad (Discworld, #12; Witches #3) |
  1671 2501 Soul Music (Discworld, #16; Death, #3) |
  1729 2554 Monstrous Regiment (Discworld, #31; Industrial Revolution, #3) |
  1793 2611 A Hat Full of Sky (Discworld, #32; Tiffany Aching, #2) |
  1844 2658 Moving Pictures (Discworld, #10; Industrial Revolution, #1) |
  1865 2677 Thief of Time (Discworld, #26; Death, #5) |
  1911 2718 The Fifth Elephant (Discworld, #24; City Watch, #5) |
  2075 2866 The Long Earth (The Long Earth, #1) |
  2092 2881 Making Money (Discworld, #36; Moist Von Lipwig, #2) |
  2153 2936 Eric (Discworld, #9; Rincewind #4) |
  2162 2944 The Truth (Discworld, #25; Industrial Revolution, #2) |
  2226 3000 Jingo (Discworld, #21; City Watch, #4) |
  2448 3200 Carpe Jugulum (Discworld #23; Witches #6) |
  2577 3317 Mort: The Play |
  2586 3325 Men at Arms: The Play |
  2623 3359 Maskerade (Discworld, #18; Witches #5) |
  2627 3362 The Last Continent (Discworld, #22; Rincewind #6) |
  2738 3462 Snuff (Discworld, #39; City Watch #8) |
  2832 3547 Wintersmith (Discworld, #35; Tiffany Aching, #3) |
  2951 3654 Unseen Academicals (Discworld, #37; Rincewind #8) |
  3037 3731 I Shall Wear Midnight (Discworld, #38; Tiffany Aching, #4) |
  3177 3858 Interesting Times (Discworld, #17; Rincewind #5) |
  3657 429 The Color of Magic (Discworld, #1; Rincewind #1) |
  3830 4445 The Castle of Llyr (The Chronicles of Prydain #3) |
  3963 4565 The Amazing Maurice and His Educated Rodents (Discworld, #28) |
  4363 4925 Nation |
  4556 5099 The Last Hero (Discworld, #27; Rincewind #7) |
  4788 5307 Raising Steam (Discworld, #40, Moist von Lipwig #3 ) |
  5650 6083 Guards! Guards!: The Play |
  5718 6144 Interesting Times: The Play |
  6395 6754 Dodger |
  7279 755 Mort (Death, #1; Discworld, #4) |
  8405 8563 The Shepherd's Crown (Discworld, #41; Tiffany Aching, #5) |
  8823 894 Guards! Guards! (Discworld, #8) |

In [27]:
show_cluster("merge:merge_clusters_by_entity_iou:234")

 merge:merge_clusters_by_entity_iou:234
n= 5
features= [(370, 0.289000004529953), (717, 0.8659999966621399), (1580, 0.289000004529953), (3982, -0.289000004529953)]
tags:
movies:
  1209 2086 Hogfather (Discworld, #20; Death, #4) |
  1844 2658 Moving Pictures (Discworld, #10; Industrial Revolution, #1) |
  2162 2944 The Truth (Discworld, #25; Industrial Revolution, #2) |
  3177 3858 Interesting Times (Discworld, #17; Rincewind #5) |
  5718 6144 Interesting Times: The Play |

In [16]:
[s for s in [x for y in ll for x in y] if 'merge' in s]

['merge:merge_clusters_by_entity_iou:97']

In [37]:
len(meta[meta.authors.str.contains("Pratchet")])

50

In [17]:
show_cluster("merge:merge_clusters_by_entity_iou:97")

 merge:merge_clusters_by_entity_iou:97
n= 21
features= [(2100, 0.5770000219345093), (2348, -0.5770000219345093), (2427, -0.5770000219345093)]
tags:
movies:
  104 1091 Cruel & Unusual (Kay Scarpetta, #4) |
  1196 2074 The Body Farm (Kay Scarpetta, #5) |
  1281 2150 Body of Evidence (Kay Scarpetta, #2) |
  1442 2296 Unnatural Exposure (Kay Scarpetta, #8) |
  1504 2351 All That Remains (Kay Scarpetta, #3) |
  1941 2745 From Potter's Field (Kay Scarpetta, #6) |
  2345 3108 Cause of Death (Kay Scarpetta, #7) |
  2717 3443 Portrait of a Killer: Jack the Ripper - Case Closed |
  3477 4127 Black Notice (Kay Scarpetta, #10) |
  4220 4797 Trace (Kay Scarpetta, #13) |
  4455 5007 Predator (Kay Scarpetta, #14) |
  4569 511 Postmortem (Kay Scarpetta, #1) |
  4631 5166 Scarpetta (Kay Scarpetta, #16) |
  4760 5282 Book of the Dead (Kay Scarpetta, #15) |
  5439 5894 Red Mist (Kay Scarpetta, #19) |
  6027 6422 The Scarpetta Factor (Kay Scarpetta, #17) |
  6532 6878 The Bone Bed (Kay Scarpetta, #20) |
  6966 7268 Port Mortuary (Kay Scarpetta, #18) |
  8622 8759 Dust (Kay Scarpetta, #21) |
  8637 8772 Flesh and Blood (Kay Scarpetta, #22) |
  8897 9005 Depraved Heart (Kay Scarpetta, #23) |

In [11]:
show_cluster("feature:646:neg")

KeyError: 'feature:646:neg'

In [13]:
def show_cluster(cid, limit=100):
    c = clusters.cluster_by_id[cid]
    print("\n", c.cluster_id)
    print("n=", c.entity_count)
    print("features=", list(zip(c.centroid.indices.tolist(), c.centroid.values.round(3).tolist())))
    print("tags:")
    for t in c.tags[:10]:
        print(f"  {t.name}: score={t.score:.3f}, count={t.count:.0f}")

    print("movies:")
    for row_idx in c.entity_indices[:limit]:
        row = meta.iloc[row_idx]
        print(" ", row_idx, row["item_id"], row["title"], "|", row.get("genres", ""))

show_cluster("feature:508:neg")
show_cluster("feature:646:neg")

KeyError: 'feature:508:neg'

In [35]:
clusters = cc.cluster_srp(
    srp,
    mode="dominant_signed",
    top_m=1,
    min_cluster_size=5,
    entity_tag_matrix=tags,
    tag_names=tag_names,
    top_k_tags=5,
    
)

In [36]:
largest = sorted(clusters.clusters, key=lambda c: c.entity_count, reverse=True)

for c in largest[:10]:
    print("\n", c.cluster_id, "n=", c.entity_count)
    print("tags:", ", ".join(f"{t.name}:{t.score:.3f}" for t in c.tags[:5]))

    for row_idx in c.entity_indices[:10]:
        row = meta.iloc[row_idx]
        print(" ", row["item_id"], row["title"], "|", row.get("genres", ""))

 feature:614:pos n= 17
tags: less than 300 ratings:0.546, animation:0.462, low budget:0.462, sci-fi:0.462, time travel:0.389
  1364 Zero Kelvin (Kjærlighetens kjøtere) (1995) | Action
  139 Target (1995) | Action|Drama
  1561 Wedding Bell Blues (1996) | Comedy
  1782 Little City (1998) | Comedy|Romance
  192 Show, The (1995) | Documentary
  2823 Spiders, The (Die Spinnen, 1. Teil: Der Goldene See) (1919) | Action|Drama
  2868 Fright Night Part II (1989) | Horror
  3047 Experience Preferred... But Not Essential (1982) | Drama
  3057 Where's Marlowe? (1999) | Comedy
  3154 Blood on the Sun (1945) | Drama|War

 feature:623:neg n= 13
tags: science:0.598, true story:0.399, genius:0.399, london:0.399, alfred hitchcock:0.399
  1040 Secret Agent, The (1996) | Drama
  1444 Guantanamera (1994) | Comedy
  1795 Callejón de los milagros, El (1995) | Drama
  1988 Hello Mary Lou: Prom Night II (1987) | Horror
  1990 Prom Night IV: Deliver Us From Evil (1992) | Horror
  200 Tie That Binds, The (1995) | Thriller
  2207 Jamaica Inn (1939) | Drama
  2768 Stiff Upper Lips (1998) | Comedy
  3041 Meatballs Part II (1984) | Comedy
  3065 Ten Benny (1997) | Drama

 feature:218:pos n= 12
tags: black comedy:0.399, writers:0.362, nudity (full frontal):0.299, tumey's dvds:0.299, adapted from:book:0.299
  1677 Critical Care (1997) | Comedy
  1679 Chairman of the Board (1998) | Comedy
  1741 Midaq Alley (Callejón de los milagros, El) (1995) | Drama
  1749 Leading Man, The (1996) | Romance
  2637 Mummy's Hand, The (1940) | Horror
  2945 Mike's Murder (1984) | Mystery
  3106 Come See the Paradise (1990) | Drama|Romance
  3748 Match, The (1999) | Comedy|Romance
  3931 Giant Gila Monster, The (1959) | Horror|Sci-Fi
  3940 Slumber Party Massacre III, The (1990) | Horror

 feature:869:pos n= 12
tags: dance:0.418, john malkovich:0.352, 06/11:0.209, christianity:0.209, biography:0.209
  1313 Mad Dog Time (1996) | Crime
  1825 Player's Club, The (1998) | Action|Drama
  2525 Alligator (1980) | Action|Horror|Sci-Fi
  2679 Finding North (1999) | Drama|Romance
  2760 Gambler, The (A Játékos) (1997) | Drama
  2934 Love Bewitched, A (El Amor Brujo) (1986) | Musical
  3136 James Dean Story, The (1957) | Documentary
  3378 Ogre, The (Der Unhold) (1996) | Drama
  3648 Abominable Snowman, The (1957) | Horror|Sci-Fi
  3867 All the Rage (a.k.a. It's the Rage) (1999) | Drama

 feature:262:neg n= 8
tags: police:3.351, comedy:0.194, franchise:0.173, less than 300 ratings:0.068, clv:0.052
  1553 Late Bloomers (1996) | Comedy
  1662 Gang Related (1997) | Crime
  2267 Mortal Thoughts (1991) | Mystery|Thriller
  2383 Police Academy 6: City Under Siege (1989) | Comedy
  2675 Twice Upon a Yesterday (1998) | Comedy|Drama|Romance
  3187 Trans (1998) | Drama
  3293 Conceiving Ada (1997) | Drama|Sci-Fi
  489 Made in America (1993) | Comedy

 feature:558:neg n= 8
tags: existentialism:0.731, dreamlike:0.731, hallucinatory:0.731, weird:0.663, surreal:0.548
  1565 Head Above Water (1996) | Comedy|Thriller
  2189 I Married A Strange Person (1997) | Animation
  2246 Stars and Bars (1988) | Comedy
  2811 With Friends Like These... (1998) | Comedy
  2998 Dreaming of Joseph Lees (1998) | Romance
  3774 House Party 2 (1991) | Comedy
  682 Tigrero: A Film That Was Never Made (1994) | Documentary|Drama
  729 Institute Benjamenta, or This Dream People Call Human Life (1995) | Drama

 feature:564:pos n= 8
tags: bd-r:0.576, oscar (best actress):0.487, adultery:0.487, british:0.487, perrot library:0.442
  1534 Bonheur, Le (1965) | Drama
  2415 Violets Are Blue... (1986) | Drama|Romance
  2776 Marcello Mastroianni: I Remember Yes, I Remember (1997) | Documentary
  3084 Home Page (1999) | Documentary
  3171 Room at the Top (1959) | Drama
  3215 Voyage of the Damned (1976) | Drama
  638 Jack and Sarah (1995) | Romance
  874 Killer: A Journal of Murder (1995) | Crime|Drama

 feature:776:neg n= 8
tags: easily confused with other movie(s) (title):0.568, nudity (topless - notable):0.346, espionage:0.169, great ending:0.169, reese witherspoon:0.169
  1767 Music From Another Room (1998) | Drama|Romance
  1791 Twilight (1998) | Crime|Drama
  2211 Secret Agent (1936) | Thriller
  2537 Beyond the Poseidon Adventure (1979) | Adventure
  3388 Harry and the Hendersons (1987) | Comedy
  386 S.F.W. (1994) | Drama
  411 You So Crazy (1994) | Comedy
  554 Trial by Jury (1994) | Thriller

 feature:54:neg n= 7
tags: overrated:1.461, controversial:1.326, nudity (topless):0.647
  1116 Single Girl, A (La Fille Seule) (1995) | Drama
  1325 Amityville: A New Generation (1993) | Horror
  1850 I Love You, Don't Touch Me! (1998) | Drama|Romance
  2251 Cabinet of Dr. Ramirez, The (1991) | Comedy
  3777 Nekromantik (1987) | Comedy|Horror
  530 Second Best (1994) | Drama
  652 301, 302 (1995) | Mystery

 feature:404:pos n= 7
tags: understated:1.096, cerebral:1.096, surreal:0.821, based on a book:0.670
  1543 Designated Mourner, The (1997) | Drama
  1891 Ugly, The (1997) | Horror|Thriller
  2191 Merry War, A (1997) | Comedy
  220 Castle Freak (1995) | Horror
  2309 Inheritors, The (Die Siebtelbauern) (1998) | Drama
  560 Beans of Egypt, Maine, The (1994) | Drama
  758 Jar, The (Khomreh) (1992) | Drama

In [5]:
clusters_iou = cc.cluster_srp(
    srp,
    mode="top_m_signed",
    top_m=1,
    min_cluster_size=5,
    activation_iou_threshold=0.5,
    entity_tag_matrix=tags,
    tag_names=tag_names,
    top_k_tags=5,
)

In [6]:
largest = sorted(clusters_iou.clusters, key=lambda c: c.entity_count, reverse=True)

for c in largest[:10]:
    print("\n", c.cluster_id, "n=", c.entity_count)
    print("tags:", ", ".join(f"{t.name}:{t.score:.3f}" for t in c.tags[:5]))

    for row_idx in c.entity_indices[:10]:
        row = meta.iloc[row_idx]
        print(" ", row["item_id"], row["title"], "|", row.get("genres", ""))

 feature:614:pos n= 17
tags: less than 300 ratings:0.546, animation:0.462, low budget:0.462, sci-fi:0.462, time travel:0.389
  1364 Zero Kelvin (Kjærlighetens kjøtere) (1995) | Action
  139 Target (1995) | Action|Drama
  1561 Wedding Bell Blues (1996) | Comedy
  1782 Little City (1998) | Comedy|Romance
  192 Show, The (1995) | Documentary
  2823 Spiders, The (Die Spinnen, 1. Teil: Der Goldene See) (1919) | Action|Drama
  2868 Fright Night Part II (1989) | Horror
  3047 Experience Preferred... But Not Essential (1982) | Drama
  3057 Where's Marlowe? (1999) | Comedy
  3154 Blood on the Sun (1945) | Drama|War

 feature:623:neg n= 13
tags: science:0.598, true story:0.399, genius:0.399, london:0.399, alfred hitchcock:0.399
  1040 Secret Agent, The (1996) | Drama
  1444 Guantanamera (1994) | Comedy
  1795 Callejón de los milagros, El (1995) | Drama
  1988 Hello Mary Lou: Prom Night II (1987) | Horror
  1990 Prom Night IV: Deliver Us From Evil (1992) | Horror
  200 Tie That Binds, The (1995) | Thriller
  2207 Jamaica Inn (1939) | Drama
  2768 Stiff Upper Lips (1998) | Comedy
  3041 Meatballs Part II (1984) | Comedy
  3065 Ten Benny (1997) | Drama

 feature:218:pos n= 12
tags: black comedy:0.399, writers:0.362, nudity (full frontal):0.299, tumey's dvds:0.299, adapted from:book:0.299
  1677 Critical Care (1997) | Comedy
  1679 Chairman of the Board (1998) | Comedy
  1741 Midaq Alley (Callejón de los milagros, El) (1995) | Drama
  1749 Leading Man, The (1996) | Romance
  2637 Mummy's Hand, The (1940) | Horror
  2945 Mike's Murder (1984) | Mystery
  3106 Come See the Paradise (1990) | Drama|Romance
  3748 Match, The (1999) | Comedy|Romance
  3931 Giant Gila Monster, The (1959) | Horror|Sci-Fi
  3940 Slumber Party Massacre III, The (1990) | Horror

 feature:869:pos n= 12
tags: dance:0.418, john malkovich:0.352, 06/11:0.209, christianity:0.209, biography:0.209
  1313 Mad Dog Time (1996) | Crime
  1825 Player's Club, The (1998) | Action|Drama
  2525 Alligator (1980) | Action|Horror|Sci-Fi
  2679 Finding North (1999) | Drama|Romance
  2760 Gambler, The (A Játékos) (1997) | Drama
  2934 Love Bewitched, A (El Amor Brujo) (1986) | Musical
  3136 James Dean Story, The (1957) | Documentary
  3378 Ogre, The (Der Unhold) (1996) | Drama
  3648 Abominable Snowman, The (1957) | Horror|Sci-Fi
  3867 All the Rage (a.k.a. It's the Rage) (1999) | Drama

 feature:262:neg n= 8
tags: police:3.351, comedy:0.194, franchise:0.173, less than 300 ratings:0.068, clv:0.052
  1553 Late Bloomers (1996) | Comedy
  1662 Gang Related (1997) | Crime
  2267 Mortal Thoughts (1991) | Mystery|Thriller
  2383 Police Academy 6: City Under Siege (1989) | Comedy
  2675 Twice Upon a Yesterday (1998) | Comedy|Drama|Romance
  3187 Trans (1998) | Drama
  3293 Conceiving Ada (1997) | Drama|Sci-Fi
  489 Made in America (1993) | Comedy

 feature:558:neg n= 8
tags: existentialism:0.731, dreamlike:0.731, hallucinatory:0.731, weird:0.663, surreal:0.548
  1565 Head Above Water (1996) | Comedy|Thriller
  2189 I Married A Strange Person (1997) | Animation
  2246 Stars and Bars (1988) | Comedy
  2811 With Friends Like These... (1998) | Comedy
  2998 Dreaming of Joseph Lees (1998) | Romance
  3774 House Party 2 (1991) | Comedy
  682 Tigrero: A Film That Was Never Made (1994) | Documentary|Drama
  729 Institute Benjamenta, or This Dream People Call Human Life (1995) | Drama

 feature:564:pos n= 8
tags: bd-r:0.576, oscar (best actress):0.487, adultery:0.487, british:0.487, perrot library:0.442
  1534 Bonheur, Le (1965) | Drama
  2415 Violets Are Blue... (1986) | Drama|Romance
  2776 Marcello Mastroianni: I Remember Yes, I Remember (1997) | Documentary
  3084 Home Page (1999) | Documentary
  3171 Room at the Top (1959) | Drama
  3215 Voyage of the Damned (1976) | Drama
  638 Jack and Sarah (1995) | Romance
  874 Killer: A Journal of Murder (1995) | Crime|Drama

 feature:776:neg n= 8
tags: easily confused with other movie(s) (title):0.568, nudity (topless - notable):0.346, espionage:0.169, great ending:0.169, reese witherspoon:0.169
  1767 Music From Another Room (1998) | Drama|Romance
  1791 Twilight (1998) | Crime|Drama
  2211 Secret Agent (1936) | Thriller
  2537 Beyond the Poseidon Adventure (1979) | Adventure
  3388 Harry and the Hendersons (1987) | Comedy
  386 S.F.W. (1994) | Drama
  411 You So Crazy (1994) | Comedy
  554 Trial by Jury (1994) | Thriller

 feature:54:neg n= 7
tags: overrated:1.461, controversial:1.326, nudity (topless):0.647
  1116 Single Girl, A (La Fille Seule) (1995) | Drama
  1325 Amityville: A New Generation (1993) | Horror
  1850 I Love You, Don't Touch Me! (1998) | Drama|Romance
  2251 Cabinet of Dr. Ramirez, The (1991) | Comedy
  3777 Nekromantik (1987) | Comedy|Horror
  530 Second Best (1994) | Drama
  652 301, 302 (1995) | Mystery

 feature:404:pos n= 7
tags: understated:1.096, cerebral:1.096, surreal:0.821, based on a book:0.670
  1543 Designated Mourner, The (1997) | Drama
  1891 Ugly, The (1997) | Horror|Thriller
  2191 Merry War, A (1997) | Comedy
  220 Castle Freak (1995) | Horror
  2309 Inheritors, The (Die Siebtelbauern) (1998) | Drama
  560 Beans of Egypt, Maine, The (1994) | Drama
  758 Jar, The (Khomreh) (1992) | Drama

In [9]:
clusters_top2 = cc.cluster_srp(
    srp,
    mode="top_m_signed",
    top_m=3,
    min_cluster_size=5,
    entity_tag_matrix=tags,
    tag_names=tag_names,
    top_k_tags=5,
)

print("top2 no merge:", len(clusters_top2.clusters))
print("top2 iou merge:", len(clusters_iou.clusters))

top2 no merge: 950
top2 iou merge: 946

In [10]:
largest_iou = sorted(clusters_iou.clusters, key=lambda c: c.entity_count, reverse=True)

for c in largest_iou[:10]:
    print("\n", c.cluster_id, "n=", c.entity_count, "features=", len(c.centroid.indices))
    print("centroid:", list(zip(c.centroid.indices.tolist(), c.centroid.values.round(3).tolist())))
    print("tags:", ", ".join(f"{t.name}:{t.score:.3f}" for t in c.tags[:5]))

    for row_idx in c.entity_indices[:10]:
        row = meta.iloc[row_idx]
        print(" ", row["title"], "|", row.get("genres", ""))

 feature:641:neg n= 54 features= 1
centroid: [(641, -1.0)]
tags: Drama:0.318, Children's:0.216, Horror:0.201, Comedy:0.180, Action:0.148
  American Strays (1996) | Action
  Children of the Corn IV: The Gathering (1996) | Horror
  Steal Big, Steal Little (1995) | Comedy
  Anna (1996) | Drama
  Zeus and Roxanne (1997) | Children's
  Temptress Moon (Feng Yue) (1996) | Romance
  Broken English (1996) | Drama
  Warriors of Virtue (1997) | Action|Adventure|Children's|Fantasy
  Head Above Water (1996) | Comedy|Thriller
  Simple Wish, A (1997) | Children's|Fantasy

 feature:218:pos n= 41 features= 1
centroid: [(218, 1.0)]
tags: Horror:0.279, Comedy:0.273, Drama:0.243, Romance:0.217, Action:0.171
  Surviving Picasso (1996) | Drama
  Amityville II: The Possession (1982) | Horror
  Message to Love: The Isle of Wight Festival (1996) | Documentary
  B*A*P*S (1997) | Comedy
  Critical Care (1997) | Comedy
  Chairman of the Board (1998) | Comedy
  Midaq Alley (Callejón de los milagros, El) (1995) | Drama
  Leading Man, The (1996) | Romance
  Welcome to Woop-Woop (1997) | Comedy
  In God's Hands (1998) | Action|Drama

 feature:614:pos n= 37 features= 1
centroid: [(614, 1.0)]
tags: Drama:0.315, Action:0.209, Horror:0.203, Thriller:0.196, Comedy:0.186
  Bad Moon (1996) | Horror
  Zero Kelvin (Kjærlighetens kjøtere) (1995) | Action
  Target (1995) | Action|Drama
  Keys to Tulsa (1997) | Crime
  Wedding Bell Blues (1996) | Comedy
  Star Maps (1997) | Drama
  Little City (1998) | Comedy|Romance
  Leather Jacket Love Story (1997) | Drama|Romance
  I Got the Hook Up (1998) | Comedy
  Show, The (1995) | Documentary

 feature:869:pos n= 36 features= 1
centroid: [(869, 1.0)]
tags: Drama:0.427, Action:0.174, Crime:0.172, Comedy:0.163, Horror:0.162
  Mad Dog Time (1996) | Crime
  Player's Club, The (1998) | Action|Drama
  Friend of the Deceased, A (1997) | Comedy|Drama
  Tie That Binds, The (1995) | Thriller
  Three Wishes (1995) | Drama
  Kidnapped (1960) | Children's|Drama
  Young and Innocent (1937) | Crime|Thriller
  Destiny Turns on the Radio (1995) | Comedy
  Overnight Delivery (1996) | Romance
  Alligator (1980) | Action|Horror|Sci-Fi

 feature:325:neg n= 35 features= 1
centroid: [(325, -1.0)]
tags: Drama:0.389, Horror:0.234, Comedy:0.214, Thriller:0.188, Adventure:0.182
  Madame Butterfly (1995) | Musical
  Two or Three Things I Know About Her (1966) | Drama
  Steal Big, Steal Little (1995) | Comedy
  Cement Garden, The (1993) | Drama
  Commandments (1997) | Romance
  Bonheur, Le (1965) | Drama
  Stag (1997) | Action|Thriller
  Playing God (1997) | Crime|Thriller
  Midaq Alley (Callejón de los milagros, El) (1995) | Drama
  Prophecy II, The (1998) | Horror

 feature:681:pos n= 34 features= 1
centroid: [(681, 1.0)]
tags: Drama:0.337, Comedy:0.279, Thriller:0.229, Sci-Fi:0.130, Adventure:0.119
  Innocents, The (1961) | Thriller
  Funeral, The (1996) | Drama
  Perfect Candidate, A (1996) | Documentary
  Jingle All the Way (1996) | Adventure|Children's|Comedy
  Marvin's Room (1996) | Drama
  Fire Down Below (1997) | Action|Drama|Thriller
  Assignment, The (1997) | Thriller
  House of Yes, The (1997) | Comedy|Drama|Thriller
  Spice World (1997) | Comedy|Musical
  Follow the Bitch (1998) | Comedy

 feature:971:neg n= 34 features= 1
centroid: [(971, -1.0)]
tags: Drama:0.325, Western:0.305, Comedy:0.252, Romance:0.229, Thriller:0.197
  Davy Crockett, King of the Wild Frontier (1955) | Western
  Six of a Kind (1934) | Comedy
  Touch (1997) | Romance
  Rhyme & Reason (1997) | Documentary
  Kissed (1996) | Romance
  Stag (1997) | Action|Thriller
  Winter Guest, The (1997) | Drama
  Meet the Deedles (1998) | Children's|Comedy
  Nil By Mouth (1997) | Drama
  Real Blonde, The (1997) | Comedy

 feature:779:pos n= 30 features= 1
centroid: [(779, 1.0)]
tags: Drama:0.298, Documentary:0.262, Comedy:0.224, Action:0.210, Romance:0.152
  Funeral, The (1996) | Drama
  Blood & Wine (1997) | Drama
  For Richer or Poorer (1997) | Comedy
  Deep Rising (1998) | Action|Horror|Sci-Fi
  Secret Agent (1936) | Thriller
  One True Thing (1998) | Drama
  One Tough Cop (1998) | Action|Drama
  Godzilla (Gojira) (1984) | Action|Sci-Fi
  Oscar and Lucinda (a.k.a. Oscar & Lucinda) (1997) | Drama|Romance
  Source, The (1999) | Documentary

 feature:582:pos n= 28 features= 1
centroid: [(582, 1.0)]
tags: Drama:0.477, Comedy:0.246, Crime:0.171, Horror:0.161, Musical:0.150
  Tin Drum, The (Blechtrommel, Die) (1979) | Drama
  Night Falls on Manhattan (1997) | Crime|Drama
  Selena (1997) | Drama|Musical
  Gabbeh (1996) | Drama
  Mad City (1997) | Action|Drama
  Two Girls and a Guy (1997) | Comedy|Drama
  Prom Night IV: Deliver Us From Evil (1992) | Horror
  Squanto: A Warrior's Tale (1994) | Adventure|Drama
  Firelight (1997) | Drama
  Men Don't Leave (1990) | Drama

 feature:427:pos n= 26 features= 1
centroid: [(427, 1.0)]
tags: Comedy:0.432, Children's:0.250, Drama:0.225, Crime:0.124, Horror:0.116
  Mr. Wrong (1996) | Comedy
  Grosse Fatigue (1994) | Comedy
  Sleeping Beauty (1959) | Animation|Children's|Musical
  Knock Off (1998) | Action
  Castle Freak (1995) | Horror
  Shadrach (1998) | Drama
  Mixed Nuts (1994) | Comedy
  Sugar Town (1999) | Comedy
  Omega Code, The (1999) | Action
  Bustin' Loose (1981) | Comedy

In [14]:
merged = cc.cluster_srp(
    srp,
    mode="dominant_signed",
    top_m=3,
    min_cluster_size=5,
    entity_tag_matrix=tags,
    tag_names=tag_names,
    top_k_tags=5,
    tag_similarity_threshold=0.5,
)

print(len(clusters.clusters), "->", len(merged.clusters))

58 -> 29

In [16]:
largest = sorted(clusters.clusters, key=lambda c: c.entity_count, reverse=True)

for c in largest[:10]:
    print("\n", c.cluster_id, "n=", c.entity_count)
    print("tags:", ", ".join(f"{t.name}:{t.score:.3f}" for t in c.tags[:5]))

    for row_idx in c.entity_indices[:10]:
        row = meta.iloc[row_idx]
        print(" ", row["item_id"], row["title"], "|", row.get("genres", ""))

 feature:614:pos n= 17
tags: Action:0.448, Drama:0.293, Comedy:0.182, Thriller:0.146, Animation:0.142
  1364 Zero Kelvin (Kjærlighetens kjøtere) (1995) | Action
  139 Target (1995) | Action|Drama
  1561 Wedding Bell Blues (1996) | Comedy
  1782 Little City (1998) | Comedy|Romance
  192 Show, The (1995) | Documentary
  2823 Spiders, The (Die Spinnen, 1. Teil: Der Goldene See) (1919) | Action|Drama
  2868 Fright Night Part II (1989) | Horror
  3047 Experience Preferred... But Not Essential (1982) | Drama
  3057 Where's Marlowe? (1999) | Comedy
  3154 Blood on the Sun (1945) | Drama|War

 feature:623:neg n= 13
tags: Drama:0.408, Comedy:0.296, Horror:0.248, Thriller:0.237, Western:0.217
  1040 Secret Agent, The (1996) | Drama
  1444 Guantanamera (1994) | Comedy
  1795 Callejón de los milagros, El (1995) | Drama
  1988 Hello Mary Lou: Prom Night II (1987) | Horror
  1990 Prom Night IV: Deliver Us From Evil (1992) | Horror
  200 Tie That Binds, The (1995) | Thriller
  2207 Jamaica Inn (1939) | Drama
  2768 Stiff Upper Lips (1998) | Comedy
  3041 Meatballs Part II (1984) | Comedy
  3065 Ten Benny (1997) | Drama

 feature:218:pos n= 12
tags: Romance:0.419, Horror:0.372, Comedy:0.371, Mystery:0.173, Sci-Fi:0.152
  1677 Critical Care (1997) | Comedy
  1679 Chairman of the Board (1998) | Comedy
  1741 Midaq Alley (Callejón de los milagros, El) (1995) | Drama
  1749 Leading Man, The (1996) | Romance
  2637 Mummy's Hand, The (1940) | Horror
  2945 Mike's Murder (1984) | Mystery
  3106 Come See the Paradise (1990) | Drama|Romance
  3748 Match, The (1999) | Comedy|Romance
  3931 Giant Gila Monster, The (1959) | Horror|Sci-Fi
  3940 Slumber Party Massacre III, The (1990) | Horror

 feature:869:pos n= 12
tags: Drama:0.363, Action:0.324, Sci-Fi:0.271, Horror:0.221, Musical:0.183
  1313 Mad Dog Time (1996) | Crime
  1825 Player's Club, The (1998) | Action|Drama
  2525 Alligator (1980) | Action|Horror|Sci-Fi
  2679 Finding North (1999) | Drama|Romance
  2760 Gambler, The (A Játékos) (1997) | Drama
  2934 Love Bewitched, A (El Amor Brujo) (1986) | Musical
  3136 James Dean Story, The (1957) | Documentary
  3378 Ogre, The (Der Unhold) (1996) | Drama
  3648 Abominable Snowman, The (1957) | Horror|Sci-Fi
  3867 All the Rage (a.k.a. It's the Rage) (1999) | Drama

 feature:262:neg n= 8
tags: Comedy:0.395, Drama:0.272, Mystery:0.231, Sci-Fi:0.203, Crime:0.169
  1553 Late Bloomers (1996) | Comedy
  1662 Gang Related (1997) | Crime
  2267 Mortal Thoughts (1991) | Mystery|Thriller
  2383 Police Academy 6: City Under Siege (1989) | Comedy
  2675 Twice Upon a Yesterday (1998) | Comedy|Drama|Romance
  3187 Trans (1998) | Drama
  3293 Conceiving Ada (1997) | Drama|Sci-Fi
  489 Made in America (1993) | Comedy

 feature:558:neg n= 8
tags: Comedy:0.474, Animation:0.369, Documentary:0.259, Drama:0.218, Thriller:0.190
  1565 Head Above Water (1996) | Comedy|Thriller
  2189 I Married A Strange Person (1997) | Animation
  2246 Stars and Bars (1988) | Comedy
  2811 With Friends Like These... (1998) | Comedy
  2998 Dreaming of Joseph Lees (1998) | Romance
  3774 House Party 2 (1991) | Comedy
  682 Tigrero: A Film That Was Never Made (1994) | Documentary|Drama
  729 Institute Benjamenta, or This Dream People Call Human Life (1995) | Drama

 feature:564:pos n= 8
tags: Drama:0.544, Documentary:0.519, Romance:0.335, Crime:0.203
  1534 Bonheur, Le (1965) | Drama
  2415 Violets Are Blue... (1986) | Drama|Romance
  2776 Marcello Mastroianni: I Remember Yes, I Remember (1997) | Documentary
  3084 Home Page (1999) | Documentary
  3171 Room at the Top (1959) | Drama
  3215 Voyage of the Damned (1976) | Drama
  638 Jack and Sarah (1995) | Romance
  874 Killer: A Journal of Murder (1995) | Crime|Drama

 feature:776:neg n= 8
tags: Thriller:0.380, Drama:0.327, Comedy:0.237, Adventure:0.230, Crime:0.203
  1767 Music From Another Room (1998) | Drama|Romance
  1791 Twilight (1998) | Crime|Drama
  2211 Secret Agent (1936) | Thriller
  2537 Beyond the Poseidon Adventure (1979) | Adventure
  3388 Harry and the Hendersons (1987) | Comedy
  386 S.F.W. (1994) | Drama
  411 You So Crazy (1994) | Comedy
  554 Trial by Jury (1994) | Thriller

 feature:54:neg n= 7
tags: Horror:0.441, Drama:0.363, Mystery:0.308, Comedy:0.263, Romance:0.186
  1116 Single Girl, A (La Fille Seule) (1995) | Drama
  1325 Amityville: A New Generation (1993) | Horror
  1850 I Love You, Don't Touch Me! (1998) | Drama|Romance
  2251 Cabinet of Dr. Ramirez, The (1991) | Comedy
  3777 Nekromantik (1987) | Comedy|Horror
  530 Second Best (1994) | Drama
  652 301, 302 (1995) | Mystery

 feature:404:pos n= 7
tags: Drama:0.544, Horror:0.497, Thriller:0.237, Comedy:0.148
  1543 Designated Mourner, The (1997) | Drama
  1891 Ugly, The (1997) | Horror|Thriller
  2191 Merry War, A (1997) | Comedy
  220 Castle Freak (1995) | Horror
  2309 Inheritors, The (Die Siebtelbauern) (1998) | Drama
  560 Beans of Egypt, Maine, The (1994) | Drama
  758 Jar, The (Khomreh) (1992) | Drama

In [22]:
for th in [0.1, 0.3, 0.5, 0.7, 0.9]:
    c = cc.cluster_srp(
        srp,
        mode="top_m_signed",
        top_m=3,
        min_cluster_size=10,
        activation_iou_threshold=th,
        entity_tag_matrix=tags,
        tag_names=tag_names,
        top_k_tags=5,
    )
    print("top3 iou", th, "clusters", len(c.clusters), "largest", max(x.entity_count for x in c.clusters), "smallest", min(x.entity_count for x in c.clusters))

top3 iou 0.1 clusters 145 largest 54 smallest 10
top3 iou 0.3 clusters 149 largest 54 smallest 10
top3 iou 0.5 clusters 149 largest 54 smallest 10
top3 iou 0.7 clusters 149 largest 54 smallest 10
top3 iou 0.9 clusters 149 largest 54 smallest 10

In [23]:
largest = sorted(c.clusters, key=lambda c: c.entity_count, reverse=True)

for c in largest[:10]:
    print("\n", c.cluster_id, "n=", c.entity_count)
    print("tags:", ", ".join(f"{t.name}:{t.score:.3f}" for t in c.tags[:5]))

    for row_idx in c.entity_indices[:10]:
        row = meta.iloc[row_idx]
        print(" ", row["item_id"], row["title"], "|", row.get("genres", ""))

 feature:641:neg n= 54
tags: Drama:0.281, Children's:0.161, Comedy:0.156, Horror:0.149, Fantasy:0.117
  1102 American Strays (1996) | Action
  1105 Children of the Corn IV: The Gathering (1996) | Horror
  119 Steal Big, Steal Little (1995) | Comedy
  1316 Anna (1996) | Drama
  1426 Zeus and Roxanne (1997) | Children's
  1514 Temptress Moon (Feng Yue) (1996) | Romance
  1519 Broken English (1996) | Drama
  1525 Warriors of Virtue (1997) | Action|Adventure|Children's|Fantasy
  1565 Head Above Water (1996) | Comedy|Thriller
  1583 Simple Wish, A (1997) | Children's|Fantasy

 feature:218:pos n= 41
tags: Comedy:0.236, Drama:0.215, Horror:0.206, Romance:0.161, Action:0.134
  1044 Surviving Picasso (1996) | Drama
  1326 Amityville II: The Possession (1982) | Horror
  1420 Message to Love: The Isle of Wight Festival (1996) | Documentary
  1490 B*A*P*S (1997) | Comedy
  1677 Critical Care (1997) | Comedy
  1679 Chairman of the Board (1998) | Comedy
  1741 Midaq Alley (Callejón de los milagros, El) (1995) | Drama
  1749 Leading Man, The (1996) | Romance
  1793 Welcome to Woop-Woop (1997) | Comedy
  1796 In God's Hands (1998) | Action|Drama

 feature:614:pos n= 37
tags: Drama:0.279, Action:0.164, Comedy:0.160, Thriller:0.156, Horror:0.150
  1168 Bad Moon (1996) | Horror
  1364 Zero Kelvin (Kjærlighetens kjøtere) (1995) | Action
  139 Target (1995) | Action|Drama
  1501 Keys to Tulsa (1997) | Crime
  1561 Wedding Bell Blues (1996) | Comedy
  1613 Star Maps (1997) | Drama
  1782 Little City (1998) | Comedy|Romance
  1851 Leather Jacket Love Story (1997) | Drama|Romance
  1886 I Got the Hook Up (1998) | Comedy
  192 Show, The (1995) | Documentary

 feature:869:pos n= 36
tags: Drama:0.378, Comedy:0.140, Action:0.136, Crime:0.129, Horror:0.120
  1313 Mad Dog Time (1996) | Crime
  1825 Player's Club, The (1998) | Action|Drama
  1871 Friend of the Deceased, A (1997) | Comedy|Drama
  200 Tie That Binds, The (1995) | Thriller
  201 Three Wishes (1995) | Drama
  2079 Kidnapped (1960) | Children's|Drama
  2209 Young and Innocent (1937) | Crime|Thriller
  228 Destiny Turns on the Radio (1995) | Comedy
  2292 Overnight Delivery (1996) | Romance
  2525 Alligator (1980) | Action|Horror|Sci-Fi

 feature:325:neg n= 35
tags: Drama:0.344, Comedy:0.185, Horror:0.173, Thriller:0.150, Adventure:0.139
  1087 Madame Butterfly (1995) | Musical
  1164 Two or Three Things I Know About Her (1966) | Drama
  119 Steal Big, Steal Little (1995) | Comedy
  1437 Cement Garden, The (1993) | Drama
  1520 Commandments (1997) | Romance
  1534 Bonheur, Le (1965) | Drama
  1636 Stag (1997) | Action|Thriller
  1647 Playing God (1997) | Crime|Thriller
  1741 Midaq Alley (Callejón de los milagros, El) (1995) | Drama
  1756 Prophecy II, The (1998) | Horror

 feature:681:pos n= 34
tags: Drama:0.299, Comedy:0.240, Thriller:0.182, Sci-Fi:0.107, Adventure:0.091
  1076 Innocents, The (1961) | Thriller
  1114 Funeral, The (1996) | Drama
  1123 Perfect Candidate, A (1996) | Documentary
  1359 Jingle All the Way (1996) | Adventure|Children's|Comedy
  1399 Marvin's Room (1996) | Drama
  1626 Fire Down Below (1997) | Action|Drama|Thriller
  1631 Assignment, The (1997) | Thriller
  1648 House of Yes, The (1997) | Comedy|Drama|Thriller
  1760 Spice World (1997) | Comedy|Musical
  1830 Follow the Bitch (1998) | Comedy

 feature:971:neg n= 34
tags: Drama:0.288, Western:0.229, Comedy:0.217, Romance:0.169, Thriller:0.156
  1008 Davy Crockett, King of the Wild Frontier (1955) | Western
  1160 Six of a Kind (1934) | Comedy
  1458 Touch (1997) | Romance
  1470 Rhyme & Reason (1997) | Documentary
  1502 Kissed (1996) | Romance
  1636 Stag (1997) | Action|Thriller
  1728 Winter Guest, The (1997) | Drama
  1822 Meet the Deedles (1998) | Children's|Comedy
  1846 Nil By Mouth (1997) | Drama
  1857 Real Blonde, The (1997) | Comedy

 feature:779:pos n= 30
tags: Drama:0.264, Comedy:0.193, Documentary:0.185, Action:0.164, Romance:0.113
  1114 Funeral, The (1996) | Drama
  1351 Blood & Wine (1997) | Drama
  1703 For Richer or Poorer (1997) | Comedy
  1762 Deep Rising (1998) | Action|Horror|Sci-Fi
  2211 Secret Agent (1936) | Thriller
  2272 One True Thing (1998) | Drama
  2307 One Tough Cop (1998) | Action|Drama
  2364 Godzilla (Gojira) (1984) | Action|Sci-Fi
  2801 Oscar and Lucinda (a.k.a. Oscar & Lucinda) (1997) | Drama|Romance
  2813 Source, The (1999) | Documentary

 feature:582:pos n= 28
tags: Drama:0.422, Comedy:0.212, Crime:0.128, Musical:0.126, Horror:0.119
  1161 Tin Drum, The (Blechtrommel, Die) (1979) | Drama
  1404 Night Falls on Manhattan (1997) | Crime|Drama
  1487 Selena (1997) | Drama|Musical
  1575 Gabbeh (1996) | Drama
  1667 Mad City (1997) | Action|Drama
  1816 Two Girls and a Guy (1997) | Comedy|Drama
  1990 Prom Night IV: Deliver Us From Evil (1992) | Horror
  2101 Squanto: A Warrior's Tale (1994) | Adventure|Drama
  2197 Firelight (1997) | Drama
  2250 Men Don't Leave (1990) | Drama

 feature:427:pos n= 26
tags: Comedy:0.373, Drama:0.200, Children's:0.186, Crime:0.092, Film-Noir:0.088
  102 Mr. Wrong (1996) | Comedy
  1174 Grosse Fatigue (1994) | Comedy
  2096 Sleeping Beauty (1959) | Animation|Children's|Musical
  2196 Knock Off (1998) | Action
  220 Castle Freak (1995) | Horror
  2293 Shadrach (1998) | Drama
  275 Mixed Nuts (1994) | Comedy
  2865 Sugar Town (1999) | Comedy
  2965 Omega Code, The (1999) | Action
  3014 Bustin' Loose (1981) | Comedy